# Book settings
title:
author: CÃ¡tedra de Fundamentos de la Ciencia de Datos
logo: docs/images/unr_logo.png
only_build_toc_files: false

repository:
  url: https://github.com/msoltadeo/fdcd
  branch: main

# Execution Settings
execute:
  execute_notebooks: off

html:
  use_repository_button: true
  use_thebe: true  # Enable Thebe

launch_buttons:
  thebe: true


# Bibliography settings
bibtex_bibfiles:
  - docs/bibliography.bib

# Sphinx settings
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]